version: '3.3'

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "danger123"
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql/data:/var/opt/mssql/data
      - /var/opt/mssql/log:/var/opt/mssql/log
      - /var/opt/mssql/secrets:/var/opt/mssql/secrets
